package com.jamub.payaccess.api.enums;

public enum ApplicationAction {
	UPDATE_USER_STATUS,
	CREATE_NEW_ADMIN_USER,
    UPDATE_ADMIN_USER,
    CREATE_NEW_BANK,
    CREATE_TRANSACTION_TICKET, CREATE_MAKER_CHECKER, MAP_PERMISSION_TO_ROLE, CREATE_NEW_ACQUIRER,
    CLOSE_TRANSACTION_TICKET, ASSIGN_TRANSACTION_TICKET
}
